input_data: /home/elsa/projects/rrg-adroit-ab/elsa/Thesis/Data/data_test_paper_pipeline
metadata_file: CRC_METADATA.csv
data_file: CRC_gene_data.csv
output_directory: /home/elsa/projects/rrg-adroit-ab/elsa/Thesis/test_paper_pipeline/output
name: TestPipelinePaper
nb_samplings: 3
cpus: 2
memory: 20G