$schema: "http://json-schema.org/draft-04/schema#"

description: snakemake configuration file

type: object

# possible entries of the config file and which type they should be
properties:
  # prefix:
  #   type: array
  input_data:
    type: string
  metadata_file:
    type: string
  data_file:
    type: string
  output_directory:
    type: string
  name:
    type: string
  # classifiers:
  #   type: array
  nb_samplings: 
    type: integer
  # classifiers_weka_name:
  #   type : object
  # classif_options:
  #   type : string
  # genome_ref_dir:
  #   type : string
  cpus:
    type: integer
  memory:
    type: string

# entries that have to be in the config file for successful validation
required:
  # - prefix
  - input_data
  - metadata_file
  - data_file
  - output_directory
  - name
  - nb_samplings
  - cpus
  - memory
  # - classifiers
  # - classifiers_weka_name
  # - classif_options
  # - genome_ref_dir