$schema: "http://json-schema.org/draft-04/schema#"

description: snakemake configuration file

type: object

# possible entries of the config file and which type they should be
properties:
  input_data:
    type: string
  metadata_file:
    type: string
  data_file:
    type: string
  output_directory:
    type: string
  name:
    type: string
  nb_samplings: 
    type: integer
  cpus:
    type: integer
  memory:
    type: string

# entries that have to be in the config file for successful validation
required:
  - input_data
  - metadata_file
  - data_file
  - output_directory
  - name
  - nb_samplings
  - cpus
  - memory