# Main entrypoint of the workflow. 
# Please follow the best practices: 
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there. 

include: "rules/common.smk"
# include: "rules/make_file_tree.smk"
include: "rules/stratified_sampling.smk"
include: "rules/training.smk"

workdir: "scripts/"

rule all:
    input:
        expand('{output_directory}/Training/Pipeline_LaunchTraining_OK.txt',output_directory = config['output_directory'])
