prefix:
  - noS1
  - noS2
  - noS3
run_name : COAD_READ_Transcript_healthy_vs_stageIV
classifiers :
  - BAYES_A1DE
  - BAYES_BN
  - BAYES_NB
  - TREES_C45
  - TREES_RF
  - TREES_CART
  - LAZY_kNN
  - FUNCTIONS_SVM
classifiers_weka_name :
  BAYES_A1DE:
    - weka : bayes.AveragedNDependenceEstimators.A1DE
    - change : A1DE
  BAYES_BN:
    - weka : bayes.BayesNet
    - change : Bayes Network
  BAYES_NB:
    - weka : bayes.NaiveBayes
    - change : Naive Bayes
  TREES_C45:
    - weka : trees.J48
    - change : C4.5
  TREES_RF:
    - weka : trees.RandomForest
    - change : Random Forest
  TREES_CART:
    - weka : trees.SimpleCart
    - change : Simple Cart
  LAZY_kNN:
    - weka : lazy.IBk
    - change : kNN
  FUNCTIONS_SVM:
    - weka : functions.smo
    - change : SVM
classif_options : /home/eclaude/Documents/These/Runs_BDML/Parameters_config_DB/nb_params_by_method.csv
genome_ref_dir : /home/eclaude/Documents/These/REF_datasets/
avg_mcc_threshold : 0.7
std_mcc : 0.1
input_path: /home/eclaude/Documents/These/Runs_BDML/TEST_SNAKEMAKE/random/
output_path: /home/eclaude/Documents/These/Runs_BDML/TEST_SNAKEMAKE/random/